# .github/workflows/ci.yml

name: Continuous Integration

# Gatilhos: roda em pushes para a branch 'main' e em qualquer Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # O job vai rodar em uma máquina virtual Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Roda o linter (Flake8) para verificar a qualidade do código
      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Roda os testes com Pytest
      - name: Test with Pytest
        run: |
          pytest