name: CI-CD Pipeline with Docker and Notifications

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with Pytest
        run: pytest

  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# Notificação Discord
  notify_discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [build_and_test, push_to_registry]
    if: always()

    steps:
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Execução do pipeline finalizada!"
          embed-title: "Status do Pipeline: ${{ needs.push_to_registry.result == 'success' && 'Sucesso' || 'Falha' }}"
          embed-description: "Commit por **${{ github.actor }}**: `${{ github.event.head_commit.message }}`"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          embed-color: "${{ needs.push_to_registry.result == 'success' && '65280' || '16711680' }}"
          embed-author-name: "${{ github.repository }}"
          embed-author-url: "${{ github.server_url }}/${{ github.repository }}"